// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['WEB_API_KEY'] ?? "",
    appId: '1:152175552069:web:200f9ff619589fbde1e52c',
    messagingSenderId: '152175552069',
    projectId: 'portfolio-web-flutter-c9ce7',
    authDomain: 'portfolio-web-flutter-c9ce7.firebaseapp.com',
    storageBucket: 'portfolio-web-flutter-c9ce7.firebasestorage.app',
    measurementId: 'G-22TYWBRSBY',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['ANDROID_API_KEY'] ?? "",
    appId: '1:152175552069:android:52c969e61ea518f7e1e52c',
    messagingSenderId: '152175552069',
    projectId: 'portfolio-web-flutter-c9ce7',
    storageBucket: 'portfolio-web-flutter-c9ce7.firebasestorage.app',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['IOS_API_KEY'] ?? "",
    appId: '1:152175552069:ios:dec254afd150da07e1e52c',
    messagingSenderId: '152175552069',
    projectId: 'portfolio-web-flutter-c9ce7',
    storageBucket: 'portfolio-web-flutter-c9ce7.firebasestorage.app',
    iosBundleId: 'com.example.portfolio',
  );
}
